version: "3.7"

services:
  web:
    build: .
    volumes:
      - .:/{$RAILS_ROOT}:cached
      - bundle_cache:/bundle_cache
      - db_data:/db
    ports:
      - 3000:3000
    environment:
      PIDFILE: /tmp/pids/server.pid
    tmpfs:
      - /tmp/pids/

volumes:
  bundle_cache:
  db_data:
