version: "3.7"

services:
  web:
    build: .
    volumes:
      - .:/{$RAILS_ROOT}:cached
      - bundle_cache:/bundle_cache
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: {$DB_USERNAME}
      DATABASE_PASSWORD: {$DB_PASSWORD}
      PIDFILE: /tmp/pids/server.pid
    tmpfs:
      - /tmp/pids/

  db:
    image: {$DB_IMAGE}
    volumes:
      - db_data:/{$DB_VOLUME}
    ports:
      - {$DB_PORTS}
    environment:
      {$DB_ENV}
volumes:
  bundle_cache:
  db_data:
